# Site settings
title: Ryan Schumacher
email: SchuStudios@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am Ryan Schumacher; Welcome to my website. I am a code monkey living in Atlanta, Georgia. I created this blog as a way to organize and share my thoughts on new technology and software. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://schustudios.com" # the base hostname & protocol for your site
twitter_username: SchuStudios
github_username:  SchuStudios
permalink: /blog/:title

# Build settings
markdown: kramdown

gems: [jekyll-sitemap]

# Custom settings
image_path: "/assets/i/"

# FOR NBA DEVELOPMENT
include: 
  - .well-known